### ISSUE TITLE
テーブルをマイグレーションで作成する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ca-training#1]
当面以下の4ステップで作成を行なっていく。

![2017-06-17 13 57 44](https://user-images.githubusercontent.com/627817/27265470-8bb4d2c4-54d1-11e7-9a60-bb2bd848eaf0.jpg)

ここは2番目の段階で、threadsテーブルを作成する。主要なカラムは下記。

- body text

**Comment by hamika** [comment]
完了しました。
threadsテーブル追加。
間違えてbodyテーブル(ここも単数形で間違え...)も作って、bundle exec rake db:migrateしてしまいました…
戻し方がわからないので、取り敢えず次のステップに進みます。

**Comment by ms2sato** [comment]
最終的にはOKにできて何よりです！Closeします！
